apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:

      - name: nginx
        image: docker.xuanyuan.me/nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ngx-service
  namespace: ngx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 8889
    targetPort: 80
    nodePort: 32100
