apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: freewenxiao/nginx-test:105
        ports:
        - containerPort: 80
